apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-controller
  labels:
    app.kubernetes.io/name: tenant-controller
    app.kubernetes.io/instance: tenant-controller
    app.kubernetes.io/component: controller
rules:
- apiGroups:
  - network.akuity.io
  resources:
  - tenants
  - tenants/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
# TODO: Add additional rules to permit this controller to manage Namespaces and
# NetworkPolicies
- apiGroups: 
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: 
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete