apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-controller
  namespace: tenant-controller
  labels:
    app.kubernetes.io/name: tenant-controller
    app.kubernetes.io/instance: tenant-controller
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tenant-controller
      app.kubernetes.io/instance: tenant-controller
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tenant-controller
        app.kubernetes.io/instance: tenant-controller
        app.kubernetes.io/component: controller
    spec:
      serviceAccount: tenant-controller
      containers:
      - name: controller
        image: tenant-controller:dev
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/tenant-controller"]
