apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-controller
  namespace: tenant-controller
  labels:
    app.kubernetes.io/name: tenant-controller
    app.kubernetes.io/instance: tenant-controller
    app.kubernetes.io/component: controller
